DROP TABLE BeneficiaryMission;
DROP TABLE InterpreterMission;
DROP TABLE Mission;
DROP TABLE Location;
DROP TABLE City;
DROP TABLE JobSkillInterpreter;
DROP TABLE AcademicSkillInterpreter;
DROP TABLE AcademicSkill;
DROP TABLE JobSkill;
DROP TABLE Unavailability;
DROP TABLE Availability;
DROP TABLE TimeSlot;
DROP TABLE Beneficiary;
DROP TABLE Interpreter;
DROP TABLE AppliUser;
DROP TABLE Transportation;
DROP TABLE Status;


CREATE TABLE Status (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR),
    hourQuota INTEGER NOT NULL
);

CREATE TABLE Transportation (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE AppliUser (
    id VARCHAR2(8 CHAR) PRIMARY KEY,
    last_name VARCHAR2(25 CHAR) NOT NULL,
    first_name VARCHAR2(25 CHAR) NOT NULL,
    birthday DATE NOT NULL,
    password VARCHAR2(50 CHAR) NOT NULL,
    mail VARCHAR2(50 CHAR) NOT NULL,
    phone VARCHAR2(25 CHAR)
);

CREATE TABLE Interpreter (
    id VARCHAR2(8 CHAR) PRIMARY KEY REFERENCES AppliUser(id),
    hourQuotaWeek INTEGER NOT NULL,
    hourQuotaYear INTEGER NOT NULL,
    isManager NUMBER(1),
    transportation INTEGER NOT NULL REFERENCES Transportation(id)
);

CREATE TABLE Beneficiary (
    id VARCHAR2(8 CHAR) PRIMARY KEY REFERENCES AppliUser(id),
    status INTEGER NOT NULL REFERENCES Status(id),
    referenceInterpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(id)
);

CREATE TABLE TimeSlot (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    startHourTime DATE NOT NULL,
    endHourTime DATE NOT NULL,
    day NUMBER(1)
);

CREATE TABLE Unavailability (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(id),
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    reason VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PKUnavailability PRIMARY KEY (interpreter, timeSlot)
);

CREATE TABLE Availability (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(id),
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    CONSTRAINT PKAvailability PRIMARY KEY (interpreter, timeSlot)
);

CREATE TABLE AcademicSkill (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE JobSkill (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE AcademicSkillInterpreter (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(id),
    skill INTEGER NOT NULL REFERENCES AcademicSkill(id),
    CONSTRAINT PKAcademicSkillInterpreter PRIMARY KEY (interpreter, skill)
);

CREATE TABLE JobSkillInterpreter (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(id),
    skill INTEGER NOT NULL REFERENCES JobSkill(id),
    CONSTRAINT PKJobSkillInterpreter PRIMARY KEY (interpreter, skill)
);

CREATE TABLE City (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2 (25 CHAR) NOT NULL,
    postalCode NUMBER(4) NOT NULL
);

CREATE TABLE Location (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(50 CHAR),
    city INTEGER NOT NULL REFERENCES City(id),
    street VARCHAR2(50 CHAR) NOT NULL,
    streetNumber VARCHAR2(8 CHAR),
    box INTEGER,
    room VARCHAR2(5 CHAR)
);

CREATE TABLE Mission (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subject VARCHAR2(25 CHAR) NOT NULL,
    status CHAR NOT NULL,
    location INTEGER NOT NULL REFERENCES Location(id),
    commentary VARCHAR2(25 CHAR),
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    jobSkill INTEGER REFERENCES JobSkill(id),
    academicSkill INTEGER REFERENCES AcademicSkill(id)
);

CREATE TABLE BeneficiaryMission (
    mission INTEGER NOT NULL REFERENCES Mission(id),
    beneficiary VARCHAR2(8 CHAR) NOT NULL REFERENCES Beneficiary(id),
    importance INTEGER NOT NULL,
    CONSTRAINT PKBeneficiaryMission PRIMARY KEY (mission, beneficiary)
);

CREATE TABLE InterpreterMission (
    mission INTEGER NOT NULL REFERENCES Mission(id),
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(id),
    CONSTRAINT PKInterpreterMission PRIMARY KEY (mission, interpreter)
);


ALTER TABLE Status ADD CONSTRAINT QuotaValue CHECK (hourQuota >= 0);

ALTER TABLE AppliUser ADD CONSTRAINT IDUser CHECK (REGEXP_LIKE(id,'^i[0-9]{7}$') OR REGEXP_LIKE(id,'^b[0-9]{7}$')); 
ALTER TABLE AppliUser ADD CONSTRAINT PhoneUser CHECK (phone IS NULL OR REGEXP_LIKE(phone,'^[0-9]+/[0-9]+\.[0-9]+\.[0-9]+$'));
ALTER TABLE AppliUser ADD CONSTRAINT MailUser CHECK (REGEXP_LIKE(mail, '.+@.+\..+'));

ALTER TABLE Interpreter ADD CONSTRAINT QuotaWeekValue CHECK (hourQuotaWeek >= 0);
ALTER TABLE Interpreter ADD CONSTRAINT QuotaYearValue CHECK (hourQuotaYear >= 0);
ALTER TABLE Interpreter ADD CONSTRAINT Responsibility CHECK (isManager IN (0, 1));

ALTER TABLE City ADD CONSTRAINT PostalCodeValue CHECK (postalCode > 999);

ALTER TABLE TimeSlot ADD CONSTRAINT DateOrder CHECK (startHourTime < endHourTime);
ALTER TABLE TimeSlot ADD CONSTRAINT TypeOfTimeSlot CHECK (day IS NULL OR day BETWEEN 0 AND 6);
ALTER TABLE TimeSlot ADD CONSTRAINT TimeSlotUnique UNIQUE (startHourTime, endHourTime, day);

ALTER TABLE Mission ADD CONSTRAINT StatusValue CHECK (status IN ('A', 'R', 'D', 'H'));
ALTER TABLE Mission ADD CONSTRAINT SkillsNeeded CHECK ((jobSkill IS NULL AND academicSkill IS NULL) OR (jobSkill IS NOT NULL AND academicSkill IS NOT NULL));

commit;