events {}
http {

    upstream my_load_balancer {
        server apache1:80 max_fails=1 fail_timeout=3s;
        server apache2:80 backup;
    }
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://my_load_balancer/;
            proxy_connect_timeout 2s;
            proxy_read_timeout 2s;
        }
    }
}