events {}
http {
    server {
        listen 80;
        server_name site-apache1.com;

        location / {
            proxy_pass http://apache1:80;
        }
    }

    server {
        listen 80;
        server_name site-apache2.com;

        location / {
            proxy_pass http://apache2:80;
        }
    }
}